
variables:
  BUILD_VERSION: $(grep 'UNBOUND_VERSION=' Dockerfile | awk -F '=' '{print $2}')
  BUILD_DATE: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
  VCS_REF: $(git describe --tags --always --dirty)

image: docker:stable-git

services:
  - name: docker:dind
    command: ["--experimental"]

before_script:
  - mkdir -p ~/.docker/cli-plugins
  - wget https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use --driver docker-container
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin docker.io

.test:
  stage: test
  script:
    - docker buildx build --platform ${PLATFORM} --tag unbound --cache-to type=local,dest=.cache/${PLATFORM} --load .
    - docker run --rm -d --name unbound unbound
    - set +o pipefail
    - docker exec unbound unbound-anchor -v | tee /dev/stderr | grep -q success
    - docker exec unbound drill -p 5053 sigok.verteiltesysteme.net @127.0.0.1 | tee /dev/stderr | grep -q NOERROR
    - docker exec unbound drill -p 5053 sigfail.verteiltesysteme.net @127.0.0.1 | tee /dev/stderr | grep -q SERVFAIL
    - docker stop unbound
  artifacts:
    paths:
      - .cache
    expire_in: 1 hour

linux/amd64:
  extends: .test
  variables:
    PLATFORM: linux/amd64

linux/arm64:
  extends: .test
  variables:
    PLATFORM: linux/arm64

linux/ppc64le:
  extends: .test
  variables:
    PLATFORM: linux/ppc64le

linux/s390x:
  extends: .test
  variables:
    PLATFORM: linux/s390x

linux/arm/v7:
  extends: .test
  variables:
    PLATFORM: linux/arm/v7

linux/arm/v6:
  extends: .test
  variables:
    PLATFORM: linux/arm/v6

deploy:
  stage: deploy
  script:
    - env
    - export BUILD_VERSION="$(grep 'UNBOUND_VERSION=' Dockerfile | awk -F '=' '{print $2}')"
    - env
    - |
      docker buildx build . --push --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6 \
      --cache-from type=local,src=.cache/linux/amd64 \
      --cache-from type=local,src=.cache/linux/arm64 \
      --cache-from type=local,src=.cache/linux/ppc64le \
      --cache-from type=local,src=.cache/linux/s390x \
      --cache-from type=local,src=.cache/linux/arm/v7 \
      --cache-from type=local,src=.cache/linux/arm/v6 \
      --label "org.opencontainers.image.created=${BUILD_DATE}" \
      --label "org.opencontainers.image.version=${BUILD_VERSION}" \
      --label "org.opencontainers.image.revision=${VCS_REF}" \
      --tag ${CI_REGISTRY_IMAGE}:${BUILD_VERSION} \
      --tag ${CI_REGISTRY_IMAGE}:latest \
      --tag docker.io/${DOCKERHUB_REPOSITORY}:${BUILD_VERSION} \
      --tag docker.io/${DOCKERHUB_REPOSITORY}:latest
    - docker run -v ${PWD}:/workspace -e DOCKERHUB_USERNAME -e DOCKERHUB_PASSWORD -e DOCKERHUB_REPOSITORY -e README_FILEPATH=/workspace/README.md peterevans/dockerhub-description
  only:
    - master
